# Config params of NewRECOGNIZER.
NAME: NewRecognizer                   # Name for humans.
TYPE: RECOGNIZER                      # Type of component.
FILE_CLASS: NewRecognizer             # Py file where initial class is located.
CLASS_NAME: NewRecognizer             # Class name to load.
VERSION: 1.0.0                        # Module id version.
ENABLED: Y                            # Module is enabled to run.
DESCRIPTION: Description of NewRecognizer. # Description for humans.
# ------ Vars of Recognizers
CLASSES: [None, New]                  # List of classes able to detect, separate by commas.
MODEL: model/model.h5                 # Path to file of model.
#FILTER_NAME: ControllerName          # Controller data source.
#FILTER_ITEM: DeviceName              # Item data source.
FILTER_LIMIT: -1                      # Elements to return from pool each time.
# ------ Other specific config vars
