# Config params of NewANALYZER.
NAME: AbnormalEventAnalyzer           # Name for humans.
TYPE: ANALYZER                        # Type of component.
FILE_CLASS: AbnormalEventAnalyzer     # Py file where initial class is located.
CLASS_NAME: AbnormalEventAnalyzer     # Class name to load.
VERSION: 1.0.0                        # Module id version.
ENABLED: Y                            # Module is enabled to run.
DESCRIPTION: Description of AbnormalEventAnalyzer. # Description for humans.
SIMULATING: Y                         # Set true if module start with sumaleted data.
SIMULATING_PATH: M:/tmp/HM-SimulatingData/ColorInfarctRecognizer_OutPut.txt     # Set path to simulated data source.
#URL_BASE:                            # Url to pool if not simulating.
# ------ Vars of Analyzers
ALWAYS_ABNORMAL: [Infarct, Fall,]     # List of events that will always be abnormal, then notify.
ALWAYS_NORMAL: [Standup, Sitdown]     # List of events that will always be normal, then don't notify.
MODEL: model/data.ab                  # Path to file of model.
#FILTER_NAME: NameRecognizer          # Recognizer data source, could be an expreg.
#FILTER_ITEM: EventDetected           # Item data source, could be an expreg.
FILTER_LIMIT: -1                      # Elements to return from pool each time.
AUTHORIZED_CHANNELS: [MailChannel,]   # Limit the channels available to send messages.
AUTHORIZED_ATTACHMENTS: ['*:*:*',]    # Limit the source allow to attach Type:Name:Item. Example *:RGB:*
MESSAGES_LIFE: 90                     # Seconds to keep messages in memory.
# ------ Other specific config vars
TIMEWINDOW: 7                         # Time in minutes (before and after) to allow occurs an events and cosider the same.
KEEPING_WEEKS: 16                     # Size in weeks of events database.
THRESHOLD: 0.5                        # Threshold to consider an event like normal. If is below is abnormal.