# Config params of NewANALYZER.
NAME: AnomalousAnalyzer               # Name for humans.
TYPE: ANALYZER                        # Type of component.
FILE_CLASS: AnomalousAnalyzer         # Py file where initial class is located.
CLASS_NAME: AnomalousAnalyzer         # Class name to load.
VERSION: 1.0.0                        # Module id version.
ENABLED: Y                            # Module is enabled to run.
DESCRIPTION: Description of AnomalousAnalyzer. # Description for humans.
# ------ Vars of Analyzers
CLASSES: [None, New]                  # List of classes able to detect, separate by commas.
MODEL: model/model.h5                 # Path to file of model.
#FILTER_NAME: NameRecognizer          # Recognizer data source.
#FILTER_ITEM: NameRecognizer          # Item data source.
FILTER_LIMIT: -1                      # Elements to return from pool each time.
# ------ Other specific config vars
