# Config params of NewRECOGNIZER.
NAME: SkeletonInfarctRecognizer       # Name for humans.
TYPE: RECOGNIZER                      # Type of component.
FILE_CLASS: SkeletonInfarctRecognizer # Py file where initial class is located.
CLASS_NAME: SkeletonInfarctRecognizer # Class name to load.
VERSION: 1.0.0                        # Module id version.
ENABLED: Y                            # Module is enabled to run.
DESCRIPTION: Description of SkeletonInfarctRecognizer. # Description for humans.
SIMULATING: Y                         # Set true if module start with sumaleted data.
SIMULATING_PATH: M:/tmp/HM-SimulatingData/CamController_OutPut.txt     # Set path to simulated data source.
#URL_BASE:                            # Url to pool if not simulating.
# ------ Vars of Recognizers
CLASSES: [None, Infarct]              # List of classes able to detect, separate by commas.
MODEL: model/skeletonModel.h5         # Path to file of model.
FILTER_NAME: 'CamController/Skeleton' # Controller data source.
#FILTER_ITEM: DeviceName              # Item data source.
FILTER_LIMIT: -1                      # Elements to return from pool each time.
# ------ Other specific config vars
MODEL_FACE: model/faceModel.h5        # Path to file of face model.