# Config params of NewRECOGNIZER.
NAME: ColorInfarctRecognizer          # Name for humans.
TYPE: RECOGNIZER                      # Type of component.
FILE_CLASS: ColorInfarctRecognizer    # Py file where initial class is located.
CLASS_NAME: ColorInfarctRecognizer    # Class name to load.
VERSION: 1.0.0                        # Module id version.
ENABLED: Y                            # Module is enabled to run.
DESCRIPTION: Description of ColorInfarctRecognizer. # Description for humans.
# ------ Vars of Recognizers
CLASSES: [None, Infarct]              # List of classes able to detect, separate by commas.
MODEL: model/rgbInfarctModel.h5       # Path to file of model.
FILTER_NAME: CamController/Person     # Controller data source.
#FILTER_ITEM: DeviceName              # Item data source.
FILTER_LIMIT: -1                      # Elements to return from pool each time.
# ------ Other specific config vars
