# Config params of ConsoleChannel.
NAME: ConsoleChannel                      # Name for humans.
TYPE: CHANNEL                         # Type of component.
FILE_CLASS: ConsoleChannel                # Py file where initial class is located.
CLASS_NAME: ConsoleChannel                # Class name to load.
VERSION: 1.0.0                        # Module id version.
ENABLED: Y                            # Module is enabled to run.
DESCRIPTION: Description of ConsoleChannel. # Description for humans.
# ------ Vars of Channels
OF: <Value>                           # Sender.
TO: [<Value>]                         # Recipients.
#CC:  [<Value>]                       # Recipients.
#BCC:  [<Value>]                      # Recipients.
SUBJECT: '\033[1;33;40m Subject: \033[0;37;48m HM: an \033[1;31;40m [event_data] \033[0;37;48m was detected!' # Subject, can use tokens.
MESSAGE: '\033[1;33;40m Message: \033[0;37;48m [analysis_phrase]' # Body message, can use tokens.
# ------ Other specific config vars
PASSWORD: <Value>                     # Sender Password