# Config params of MailChannel.
NAME: MailChannel                     # Name for humans.
TYPE: CHANNEL                         # Type of component.
FILE_CLASS: MailChannel               # Py file where initial class is located.
CLASS_NAME: MailChannel               # Class name to load.
VERSION: 1.0.0                        # Module id version.
ENABLED: Y                            # Module is enabled to run.
DESCRIPTION: Description of MailChannel. # Description for humans.
# ------ Vars of Channels
TO: [gavit0rojas@gmail.com,]                         # Recipients.
MESSAGE: '<div style="float: left;margin-right: 5px; padding-top: 5px;">HM: an</div><div style="float: left;margin-right: 5px;font-size: large;font-weight: bold;color: red;">[event_data]</div><div style="float: left;margin-right: 5px;padding-top: 5px;">was detected</div>. <br/><br/>[analysis_phrase]' # Body message, can use tokens.
# ------ Other specific config vars
FROM: profesorgavit0@gmail.com                         # Sender.
USER: profesorgavit0@gmail.com                         # Sender User.
PASSWORD: 4564gpfpxdPP*                     # Sender Password.
SUBJECT: 'HM: an [event_data] was detected!' # Subject, can use tokens.
#CC:  [<Value>]                       # Recipients.
#BCC:  [<Value>]                      # Recipients.
SMTP: smtp.gmail.com                  # Server.
PORT: 587                             # Port.