# Config params of cam controller.
NAME: CamController                   # Name for humans.
MACHINE_NAME: CamController           # Name for no Humans.
CLASS_NAME: CamController             # Class name to load.
VERSION: 1.0.0                        # Modele id version.
DESCRIPTION: Module to control cam RGB devices. # Description for humans.
SAMPLING: 0.1                         # Sampling rate in frame per second.
ENABLED: True                         # Module is enabled to run