# Config params of cam controller.
NAME: CamController                   # Name for humans.
MACHINE_NAME: CamController           # Name for no Humans.
CLASS_NAME: CamController             # Class name to load.
VERSION: 1.0.0                        # Module id version.
DESCRIPTION: Module to control cam RGB devices. # Description for humans.
SAMPLING: 0.0                         # Sampling rate to control frame per second.
ENABLED: Y                            # Module is enabled to run
# ------
FRAME_WIDTH: 320                      # With of image
FRAME_HEIGHT: 240                     # Height of image